### ISSUE TITLE
is it intended to map long utterance to two character?

### ISSUE THREAD

**Issue by rianrajagede** [hyperforest/Quran-Project#1]
from demo example, when extracting word الله it gives:

```
[('alif', '0'), ('lam', '0'), ('lam', 'fathah'), ('alif', '0'), ('ha', 'dhammah')]
```

there are two `alif` there. I also see it happens in the second word of second ayat of Al-lkhlas, there are two `shad` characters to handle ّـ (tasydid). is it intended behaviour?

**update**: I've found it is not caused by the program, but from the input file

**Comment by hyperforest** [comment]
Thank you, but in the latest version it only concerns on the letters, because I think considering the harakat (fathah, tasydid, etc.) is a more complex thing to do that I could handle it by myself.
